### ISSUE TITLE
issue of f-string in snakemake and python 3.12 makes extra whitespaces in get_input_fastqs

### ISSUE THREAD

**Issue by realzhang** [simonlabcode/bam2bakR#8]
Dear authors:
In workflow/rules/common.smk, the f-string in glob.glob to match input fastq filenames may introduce one whitespace before and after "fastq_path". refer to:
https://github.com/snakemake/snakemake/issues/2480
I've changed the f-string into '+' to concat the strings.
Thanks for your great tools!

**Comment by isaacvock** [comment]
Hello,

Thank you very much for flagging this. Unfortunately there is another Python 3.12 [related issues](https://github.com/snakemake/snakemake/issues/2459) that will likely force bam2bakR users to run Snakemake in an environment with a Python version < 3.12 installed. I have updated the documentation accordingly and will work on a patch to fix these issues. I'll keep this issue opened until that patch is released.

Thank you for your kind words,
Isaac

**Comment by isaacvock** [comment]
The issue has been addressed in version 3.0.0 of bam2bakR (though technically it is [no longer a problem](https://github.com/snakemake/snakemake/pull/2649) for version 8.4.0+ of Snakemake). This update also includes an unrelated significant decrease in bam2bakR's runtime, discussed in the updated README. 

Let me know if you have any questions,
Isaac
